### ISSUE TITLE
BLEU evaluation code is wrong

### ISSUE THREAD

**Issue by jind11** [freesunshine0316/RaST-plus#3]
hi, thank you for sharing this source code. I found one bug in lines 28-31 in the score.py file (https://github.com/freesunshine0316/RaST-plus/blob/0a509b67b151d584cc2d6e24d1baf91d3d7798af/score.py#L28). Here to calculate the corpus_bleu score, reference and hypothesis sentences need to be as lists instead of strings. Please refer to the NLTK document for more details: https://www.nltk.org/_modules/nltk/translate/bleu_score.html.
Could you help check this code bug and make the corresponding correction in both this source code and paper? Thank you so much!

**Comment by freesunshine0316** [comment]
I'll get back ASAP.

**Comment by Mary-qingqing12131** [comment]
following[]( _https://www.nltk.org/_modules/nltk/translate/bleu_score.html._)
I changed the score calculating method：bleu1s = corpus_bleu([[r.split()] for r in references], [candidate.split() for candidate in candidates], weights=(1.0, 0.0, 0.0, 0.0)) the bleu scores are changed on rewrite dataset.

**Comment by freesunshine0316** [comment]
Hi All, 

The bug has been fixed in our [HCT](https://github.com/lisjin/hct) work, and please refer to the reported numbers in that paper for comparison. I just fixed the this bug in this repository as well if you want to work on it.
