### ISSUE TITLE
COAI Competition

### ISSUE THREAD

**Issue by duongkstn** [freesunshine0316/RaST-plus#4]
Hi, Can you give me link of COAI competition ?
It is really hard to run your code without having COAI competition data. I just have data of Rewrite and Restoration, but I do not know how to run `data_preprocess` folder with Rewrite and Restoration. Can you clearly explain how to run in my situation or explain about COAI data format ?

thanks,

**Comment by freesunshine0316** [comment]
Hi 
You can refer to [this script](https://github.com/freesunshine0316/RaST-plus/blob/main/data_preprocess/1_to_tsv.py) to preprocess your data. Given an instance of 3-turns, the resulting instance should be in the format of
```
turn-2 [SEP] turn-1 | cur-turn *\tREF
```
where ```REF``` is the reference. If there's no reference and you only want decoding, then the format is:
```
turn-2 [SEP] turn-1 | cur-turn *
```

One example is 
```
我 要 去 巴 黎 了 [SEP] 一 定 要 去 埃 菲 尔 铁 塔 | 它 是 哪 年 建 的 *    埃 菲 尔 铁 塔 是 哪 年 建 的
```
The four spaces after "*" represent the "\t" symbol.
